# Generated by Django 4.0.3 on 2022-03-24 16:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=True, populate_from='title', unique_with=('publish_date', 'category', 'auther')),
        ),
    ]
