# Generated by Django 4.0.3 on 2022-03-24 17:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0006_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, null=True, populate_from='title', unique_with=['auther', 'publish_date']),
        ),
    ]
