# Generated by Django 4.0.3 on 2022-03-24 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryApp', '0007_alter_item_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orderitem',
            new_name='BuyOrderitem',
        ),
        migrations.CreateModel(
            name='IssueOrderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryApp.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items1',
            field=models.ManyToManyField(to='libraryApp.issueorderitem'),
        ),
    ]
