# Generated by Django 4.0.3 on 2022-03-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0008_rename_orderitem_buyorderitem_issueorderitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items1',
            new_name='itemss',
        ),
    ]
