# Generated by Django 4.0.3 on 2022-03-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0009_rename_items1_order_itemss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='StateName',
            field=models.CharField(max_length=100),
        ),
    ]
